name: run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
        
    steps:
      - uses: actions/checkout@v2

      - name: install requirements
        run: pip install -r requirements.txt
        
      - name: run tests
        run: coverage run -m unittest; coverage lcov
        
      - name: run flake8
        run: flake8 tlv8

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: coverage.lcov
        

